# Write your MySQL query statement below
SELECT S.STUDENT_ID, S.STUDENT_NAME, SB.SUBJECT_NAME,
(
    SELECT COUNT(1) FROM EXAMINATIONS
    WHERE STUDENT_ID =  S.STUDENT_ID
    AND SUBJECT_NAME = SB.SUBJECT_NAME
) AS ATTENDED_EXAMS
FROM STUDENTS S
JOIN SUBJECTS SB
ORDER BY S.STUDENT_ID, SB.SUBJECT_NAME;
